# Generated by Django 4.2.9 on 2024-05-05 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('p_nombre', models.CharField(max_length=45, verbose_name='Primer nombre')),
                ('s_nombre', models.CharField(blank=True, max_length=45, null=True, verbose_name='Segundo nombre')),
                ('apellido_pat', models.CharField(max_length=45, verbose_name='Apellido paterno')),
                ('apellido_mat', models.CharField(max_length=45, verbose_name='Apellido materno')),
                ('fecha_nac', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=45, null=True, verbose_name='Dirección')),
                ('numero_apoderado', models.IntegerField(blank=True, null=True, verbose_name='Celular apoderado')),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_asig', models.CharField(max_length=45, verbose_name='Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='AñoCurso',
            fields=[
                ('id_añocurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('p_nombre', models.CharField(max_length=45, verbose_name='Primer nombre')),
                ('s_nombre', models.CharField(blank=True, max_length=45, null=True, verbose_name='Segundo nombre')),
                ('apellido_pat', models.CharField(max_length=45, verbose_name='Apellido paterno')),
                ('apellido_mat', models.CharField(max_length=45, verbose_name='Aperllido materno')),
                ('correo', models.CharField(max_length=45, verbose_name='Correo')),
                ('celular', models.IntegerField(blank=True, null=True, verbose_name='Celular')),
            ],
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id_prediccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('sugerencia', models.CharField(blank=True, max_length=45, null=True, verbose_name='Sugerencia')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.alumno', verbose_name='Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id_calificaciones', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Calificacion')),
                ('fecha', models.DateField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.alumno', verbose_name='Alumno')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.asignatura', verbose_name='Asignatura')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profesor', verbose_name='Profesor'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='año_cursado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='home.añocurso', verbose_name='Año cursado'),
        ),
    ]
