# Generated by Django 4.2.9 on 2024-07-19 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('p_nombre', models.CharField(max_length=45, verbose_name='Primer nombre')),
                ('s_nombre', models.CharField(blank=True, max_length=45, null=True, verbose_name='Segundo nombre')),
                ('apellido_pat', models.CharField(max_length=45, verbose_name='Apellido paterno')),
                ('apellido_mat', models.CharField(max_length=45, verbose_name='Apellido materno')),
                ('fecha_nac', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=45, null=True, verbose_name='Dirección')),
                ('numero_apoderado', models.IntegerField(blank=True, null=True, verbose_name='Celular apoderado')),
            ],
            options={
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_asig', models.CharField(max_length=45, verbose_name='Asignatura')),
            ],
            options={
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='AñoCurso',
            fields=[
                ('id_añocurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipousuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipo Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('p_nombre', models.CharField(max_length=45, verbose_name='Primer nombre')),
                ('s_nombre', models.CharField(blank=True, max_length=45, null=True, verbose_name='Segundo nombre')),
                ('apellido_pat', models.CharField(max_length=45, verbose_name='Apellido paterno')),
                ('apellido_mat', models.CharField(max_length=45, verbose_name='Apellido materno')),
                ('correo', models.CharField(max_length=45, verbose_name='Correo')),
                ('celular', models.IntegerField(blank=True, null=True, verbose_name='Celular')),
                ('cursos', models.ManyToManyField(to='home.añocurso', verbose_name='Cursos')),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipousuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id_prediccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('sugerencia', models.CharField(blank=True, max_length=45, null=True, verbose_name='Sugerencia')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.alumno', verbose_name='Alumno')),
            ],
            options={
                'verbose_name_plural': 'Predicciones',
            },
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id_calificaciones', models.AutoField(primary_key=True, serialize=False)),
                ('eva1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Eva 1')),
                ('eva2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Eva 2')),
                ('eva3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Eva 3')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.alumno', verbose_name='Alumno')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.asignatura', verbose_name='Asignatura')),
            ],
            options={
                'verbose_name_plural': 'Calificaciones',
            },
        ),
        migrations.AddField(
            model_name='asignatura',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.añocurso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profesor', verbose_name='Profesor'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='año_cursado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='home.añocurso', verbose_name='Año cursado'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='tipo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipousuario'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
