# Generated by Django 4.2.9 on 2024-05-06 05:07

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('run_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('p_nombre', models.CharField(max_length=45, verbose_name='Primer nombre')),
                ('s_nombre', models.CharField(blank=True, max_length=45, null=True, verbose_name='Segundo nombre')),
                ('apellido_pat', models.CharField(max_length=45, verbose_name='Apellido paterno')),
                ('apellido_mat', models.CharField(max_length=45, verbose_name='Apellido materno')),
                ('fecha_nac', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=45, null=True, verbose_name='Dirección')),
                ('numero_apoderado', models.IntegerField(blank=True, null=True, verbose_name='Celular apoderado')),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_asig', models.CharField(max_length=45, verbose_name='Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='AñoCurso',
            fields=[
                ('id_añocurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('p_nombre', models.CharField(max_length=45, verbose_name='Primer nombre')),
                ('s_nombre', models.CharField(blank=True, max_length=45, null=True, verbose_name='Segundo nombre')),
                ('apellido_pat', models.CharField(max_length=45, verbose_name='Apellido paterno')),
                ('apellido_mat', models.CharField(max_length=45, verbose_name='Aperllido materno')),
                ('correo', models.CharField(max_length=45, verbose_name='Correo')),
                ('celular', models.IntegerField(blank=True, null=True, verbose_name='Celular')),
            ],
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id_prediccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('sugerencia', models.CharField(blank=True, max_length=45, null=True, verbose_name='Sugerencia')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.alumno', verbose_name='Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_student', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(related_name='custom_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_users', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id_calificaciones', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Calificacion')),
                ('fecha', models.DateField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.alumno', verbose_name='Alumno')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.asignatura', verbose_name='Asignatura')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profesor', verbose_name='Profesor'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='año_cursado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='home.añocurso', verbose_name='Año cursado'),
        ),
    ]
