# Generated by Django 4.2.9 on 2024-05-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='apellido_mat',
            field=models.CharField(max_length=45, verbose_name='apellido materno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido_pat',
            field=models.CharField(max_length=45, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='numero_apoderado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Celular apoderado'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='p_nombre',
            field=models.CharField(max_length=45, verbose_name='Primer nombre'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='s_nombre',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Segundo nombre'),
        ),
    ]
