# Generated by Django 4.2.9 on 2024-05-06 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='run_alumno',
            new_name='id_alumno',
        ),
    ]
