# Generated by Django 4.2.9 on 2024-05-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_run_alumno_alumno_id_alumno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
