# Generated by Django 3.2.6 on 2024-07-19 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
